name: "Terraform RDS"

on:
  push:
   branches:
   - main
   paths:
   - terraform/**

env:
 # verbosity setting for Terraform logs
 TF_LOG: INFO
 TF_VAR_db_password: ${{ secrets.BD_PASSWORD }}
 # Credentials for deployment to AWS
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
 terraform:
   name: "Terraform"
   runs-on: ubuntu-latest
   defaults:
     run:
       shell: bash
       working-directory: ./terraform

   steps:
     - name: Checkout repository
       uses: actions/checkout@v2
 
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
       with:
         terraform_version: 1.0.0
    
     - name: Terraform init
       id: init
       run: terraform init

     - name: Destroy Specific Resource
       run: terraform destroy -target=aws_security_group.rds_secgrptechchallenge -auto-approve

     - name: Terraform Refresh
       run: terraform refresh

     - name: Terraform Plan
       run: terraform plan -out=tfplan

     - name: Terraform Apply
       run: terraform apply -auto-approve tfplan